### ISSUE TITLE
run.sh: 38: [[: not found

### ISSUE THREAD

**Issue by ajacques** [rancher/system-agent-installer-k3s#19]
Using Rancher v2.7.3, I tried to upgrade my k3s cluster from v1.25.7 to v1.25.9. It failed to upgrade and gave me an error telling me to check the journalctl for the `rancher-system-agent` log. I did and found:

Snippet:
```
+ LAST_START_LINE=181713"
+ [[ 181713 -gt 0 ]]"
/var/lib/rancher/agent/work/20230501-055459/f638341584bb593bbe43113259dff418bf9c670265b435ebac00359e037bf689_0/run.sh: 38: [[: not found"
+ cat k3s-service.txt"
+ LAST_LOGS=Apr 26 07:19:26 nuc-server k3s[1147]: E0426 07:19:26.730519    1147 kubelet_volumes.go:245] \"[...] unrelated old logs
```

I found the commit that seems to have introduced this code: 7fd5c1755825dc1c3060d1e3a7b240c5df19921c. This script seems to run with `/bin/sh` as per the shebang in the script, but the `/bin/sh` command provided by default with Ubuntu Server 22.04 LTS does not provide this command. It seems that `/bin/sh` is `ash`. I was able to workaround this by temporarily symlinking `/bin/sh` to `/bin/bash`, however I suspect other users may hit this problem.

In addition, this `cat k3s-service.txt` command has a habit of dumping a huge amount of old log data to the rancher-system-agent unit which makes debugging it harder.

Not sure if this should be opened in the main rancher repo though.

**Comment by brandond** [comment]
@HarrisonWAffel can you take a look at this?

The complaint about dumping the entire systemd log out to disk and then grepping through it is also valid; I would like to see the whole `LAST_START_LINE` bit reimplemented using journalctl's `--since=DATE` flag and without dumping anything out to disk.

**Comment by brandond** [comment]
We should also add a shellcheck validation to the PR CI to ensure that we only use posix shell expressions.

**Comment by brandond** [comment]
Just out of curiosity, can you confirm which versions you were upgrading from and to? `v1.25.9` is the most recent patch release available for 1.25.

**Comment by ajacques** [comment]
> @ajacques, can you confirm which versions you were upgrading from and to? `v1.25.9` is the most recent patch release available for 1.25.

You're correct, I upgraded from `v1.25.7` to `v1.25.9`, not `v1.25.10`.

**Comment by rancher-max** [comment]
Validated this now works using all of the available versions on rancher v2.7.3:
<img width="1447" alt="image" src="https://user-images.githubusercontent.com/55997940/235802403-843c5f32-9c7e-47e5-8695-c87954b54abc.png">



All created with Ubuntu 22.04 LTS (snippet taken from 1.25 cluster)

```
  nodeInfo:
    architecture: amd64
    bootID: 67579d32-001a-4af5-8ada-beedd6e77507
    containerRuntimeVersion: containerd://1.6.19-k3s1
    kernelVersion: 5.15.0-60-generic
    kubeProxyVersion: v1.25.9+k3s1
    kubeletVersion: v1.25.9+k3s1
    machineID: 7a0d9d798d7a471981c4294a126ac410
    operatingSystem: linux
    osImage: Ubuntu 22.04.2 LTS
    systemUUID: 7a0d9d798d7a471981c4294a126ac410
```
